# Generated by Django 4.2.2 on 2023-06-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_phone_number_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
